site_name: "Renu Kumari"
site_description: "A personal webpage showcasing education, experience, and background"
site_author: "RK"

theme:
  name: material
  features:
    - navigation.top
    - navigation.sections
    - search.suggest
    - content.code.copy

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/rkclimate20
    - icon: fontawesome/solid/envelope
      link: mailto:kumarirenu18@gmail.com

nav:
  - Home: index.md
  - About Me: about.md
  - Education: education.md
  - Experience and Awards: experience.md
  - Publications: publications.md
  - Skills: skills.md
  - Outreach: workshop.md 
  - Contact: contact.md
